---
title: "Population growth rates from Living Planet Database"
format: pdf
---

## Set up

```{r}
# load libraries
library(tidyverse)
library(colorspace)
```

Load the output from `calculate_growth_rates.R`. This is a data frame with the average, minimum, maximum, and standard deviation of the annual growth rates for 2567 populations. These are the 600 species for which there was data in the Living Planet Database that were included in the threat maps.

```{r}
df = readRDS("outputs/lpd_fw_growthrates.rds")
```


# Distribution of the growth rates

```{r, echo = FALSE}

# custom function to plot histograms

hist_plot = function(dat = df, varname, varlabel){
  
  # get limits for the plot axes and fill color
  subdf = select(dat, c({{varname}}))
  limit = max(c(abs(min(subdf[,1], na.rm =T)), max(subdf[,1], na.rm = T)))
  
  # histogram
  p = ggplot(data = dat) +
    geom_histogram(aes(x ={{varname}}, 
                       fill = ..x..), 
                   bins = 25, 
                   linewidth = .1, 
                   col = "grey10") +
    facet_wrap(~Class, scales = "free_y") +
    xlim(c(-limit, limit)) +
    labs(x = varlabel, 
         y = "Number of populations",
         fill = "Growth rate") +
    scale_y_sqrt() +
    colorspace::scale_fill_continuous_divergingx(palette = "Zissou 1", 
                                                 limits = c(-limit, limit),
                                                 rev = TRUE) +
    hrbrthemes::theme_ipsum_rc() +
    theme(legend.position = "bottom")
  
  return(p)
  
}
```

```{r}
hist_plot(dat = df, mean, "Average growth rate")
hist_plot(dat = df, min, "Minimum growth rate")
hist_plot(dat = df, max, "Maximum growth rate")
hist_plot(dat = df, sd, "Growth rate SD")
```

